# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sap_hana_install_files_bucket: sap-deployment-media
sap_hana_product_version: Cockpit
sap_product_and_version: 'HANA/{{ sap_hana_product_version }}'
sap_product_vars:
  'HANA/Cockpit':
    sap_hana_install_file_name: 'SAPHANACOCKPIT14.*\.SAR'
    sap_hana_upgrade_file_name: 'IMDB.*\.SAR'
    sap_hana_sapcar_file_name: SAPCAR_1320-80000935.EXE
    sap_hostagent_rpm_file_name: saphostagentrpm_44-20009394.rpm
sap_hostagent_rpm_remote_path: "/hana/shared/software"
sap_hana_data_partition_name: hanadata
sap_hana_backup_partition_name: hanabackup
sap_hana_shared_mountpoint: /hana/shared
sap_hana_data_mountpoint: /hana/data
sap_hana_log_mountpoint: /hana/log
sap_hana_usr_mountpoint: /usr/sap
sap_hana_backup_mountpoint: /hanabackup
sap_hana_sid: BG1
sap_hana_user: '{{ sap_hana_sid | lower }}adm'
sap_sapsys_gid: 2626
sap_hana_system_uid: 2525
sap_hana_instance_name: '{{ ansible_hostname }}'
sap_hana_instance_number: "00"
sap_preconfigure_modify_etc_hosts: true
sap_domain: automation.local
sap_hana_env_type: development
sap_hana_mem_restrict: "n"
sap_hana_deployment_create_initial_tenant: 'y'
# sap_hana_password is required unless all of the other passwords are set.
# It defaults to an empty string for those cases where all the other passwords are
# set, to avoid an undefined variable error.
sap_hana_password: ''
sap_hana_ase_user_password: '{{ sap_hana_password }}'
sap_hana_db_system_password: '{{ sap_hana_password }}'
sap_hana_common_master_password: '{{ sap_hana_password }}'
sap_hana_root_password: '{{ sap_hana_password }}'
sap_hana_sapadm_password: '{{ sap_hana_password }}'
sap_hana_sidadm_password: '{{ sap_hana_password }}'
sap_hana_fast_restart: false

# Backint install vars
sap_hana_backint_bucket_name: ''
sap_hana_backint_install: '{{ sap_hana_backint_bucket_name | length > 0 }}'
backint_temp_path: /tmp/backint-gcs-install.sh
backint_dir: "/usr/sap/{{ sap_hana_sid }}/SYS/global/hdb/opt/backint"
backint_config_path: "{{ backint_dir }}/backint-gcs/parameters.txt"

sap_hana_disks:
  - { name: data, partition_path : "{{ sap_hana_data_partition_name }}"}
  - { name: backup, partition_path : "{{ sap_hana_backup_partition_name }}"}

sap_hana_logvols:
  shared:
    size: "{{ sap_hana_shared_size }}"
    vol: "{{ sap_hana_data_partition_name }}" 
    mountpoint: "{{ sap_hana_shared_mountpoint }}"
    fstype: xfs
  data:
    size: "{{ sap_hana_data_size }}"
    vol: "{{ sap_hana_data_partition_name }}"
    mountpoint: "{{ sap_hana_data_mountpoint }}"
    fstype: xfs
  log:
    size: "{{ sap_hana_log_size }}"
    vol: "{{ sap_hana_data_partition_name }}"
    mountpoint: "{{ sap_hana_log_mountpoint }}"
    fstype: xfs
  usr:
    size: "{{ sap_hana_usr_size }}"
    vol: "{{ sap_hana_data_partition_name }}"
    mountpoint: "{{ sap_hana_usr_mountpoint }}"
    fstype: xfs
  backup:
    size: "{{ sap_hana_backup_size}}"
    vol: "{{ sap_hana_backup_partition_name }}"
    mountpoint: "{{ sap_hana_backup_mountpoint }}"
    fstype: xfs
